#pragma once
#include "class/define.h"
#include "class/Screen.h"
#include "class/Drawable.h"
#include "class/BMimage.h"
#include "class/AAtext.h"
#include "class/UserInput.h"
#include "class/PlainWindow.h"
#include "class/InputBox.h"
